# Generated by Django 2.2.24 on 2021-07-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0014_filename_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='groups',
            field=models.ManyToManyField(blank=True, to='thesaurus.Group'),
        ),
    ]
